development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://my-private-pub.herokuapp.com/faye"
  secret_token: "7e4deb07fb1ae4a4fbd5aaf2a6621390e65a162d928ea7826f00e9e3725ca394"
  signature_expiration: 3600 # one hour
