development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://.herokuapp.com/faye"
  secret_token: "71196f3a27eb813654a9bb58419ee45a3de4b4d3e8d3769c99be065680c5ce5b"
  signature_expiration: 3600 # one hour
